name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for Client
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Client dependencies
        run: cd client && npm install

      - name: Build Client
        run: cd client && npm run build

      - name: Deploy Client to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git fetch --all --unshallow
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME_CLIENT }}.git main
