name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Login to Heroku
      uses: heroku/authentication-action@v2
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

    - name: Install client dependencies
      run: |
        cd client
        npm install

    - name: Build client
      run: |
        cd client
        npm run build

    - name: Deploy to Heroku (client)
      run: |
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME_CLIENT }}
        git subtree push --prefix client heroku main

  deploy-server:
    runs-on: ubuntu-latest
    needs: deploy-client

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Login to Heroku
      uses: heroku/authentication-action@v2
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

    - name: Install server dependencies
      run: |
        cd server
        npm install

    - name: Build server
      run: |
        cd server
        npm run build

    - name: Deploy to Heroku (server)
      run: |
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME_SERVER }}
        git subtree push --prefix server heroku main

